# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Teste
                                 A QGIS plugin
 Teste apenas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-23
        copyright            : (C) 2023 by Tchéllo
        email                : marcelo_lopes93@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Teste class from file Teste.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Teste import Teste
    return Teste(iface)
